apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: masterinfra-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    prometheus: kube-prometheus
spec:
  groups:
    - name: kubernetes.rules
      interval: 30s
      rules:
        # Node down alert
        - alert: NodeDown
          expr: up{job="node-exporter"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Node {{ $labels.instance }} is down"
            description: "Node {{ $labels.instance }} has been down for more than 1 minute"

        # High CPU usage
        - alert: HighCPUUsage
          expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage on {{ $labels.instance }}"
            description: "CPU usage is above 80% for more than 5 minutes on {{ $labels.instance }}"

        # High memory usage
        - alert: HighMemoryUsage
          expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "High memory usage on {{ $labels.instance }}"
            description: "Memory usage is above 90% for more than 5 minutes on {{ $labels.instance }}"

        # Pod crash looping
        - alert: PodCrashLooping
          expr: increase(kube_pod_container_status_restarts_total[15m]) > 5
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has restarted more than 5 times in 15 minutes"

    - name: website.rules
      interval: 30s
      rules:
        # Website down
        - alert: WebsiteDown
          expr: up{job="website-nginx"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Website masterinfra.net is down"
            description: "Website has been down for more than 1 minute"

        # High HTTP error rate
        - alert: HighHTTPErrorRate
          expr: rate(nginx_ingress_controller_requests{status=~"5.."}[5m]) / rate(nginx_ingress_controller_requests[5m]) * 100 > 5
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High HTTP 5xx error rate"
            description: "HTTP 5xx error rate is above 5% for more than 2 minutes"

        # SSL certificate expiring
        - alert: SSLCertificateExpiring
          expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: "SSL certificate expiring soon"
            description: "SSL certificate for {{ $labels.instance }} expires in less than 7 days"