---
# ServiceMonitor para Website NGINX metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: website-nginx-metrics
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    prometheus: kube-prometheus
    app: website
spec:
  namespaceSelector:
    matchNames:
      - website
  selector:
    matchLabels:
      app: waf-metrics
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      honorLabels: true

---
# ServiceMonitor para NGINX Ingress Controller
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-controller-metrics
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    prometheus: kube-prometheus
    app: ingress-nginx
spec:
  namespaceSelector:
    matchNames:
      - ingress-nginx
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      honorLabels: true

---
# ServiceMonitor para cert-manager
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager-metrics
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    prometheus: kube-prometheus
    app: cert-manager
spec:
  namespaceSelector:
    matchNames:
      - cert-manager
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
  endpoints:
    - port: tcp-prometheus-servicemonitor
      path: /metrics
      interval: 60s
      honorLabels: true

---
# ServiceMonitor para kube-state-metrics (se não existir)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics-custom
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    prometheus: kube-prometheus
    app: kube-state-metrics
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      honorLabels: true